### ISSUE TITLE
Machines not operating

### ISSUE THREAD

**Issue by Logos01** [theflogat/Technomancy-Origin#3]
Running ResonantRise modpack (2.x -- issue has persisted across multiple releases).  No Botania.  

Behavior seen:  
No machines have GUIs.  No machines seem to create any outputs.  Node fabricators will accept RF but will not activate.  Ignis Incinerators (on newest pack) will not accept inputs nor attempt to absorb Ignis.  Node generators do not generate RF, and do not absorbe vis from nodes.  Essentia dynamos do not absorb essentia, do not produce RF.  Blood dynamos do not aborb LP, do not produce RF.  Quantum bellows cannot be placed anywhere in the world (regardless of if using with Infernal Furnace or with Alchemical Furnace).  

No errors appear in the server logs when attempting these behaviors; they simply produce no effects.

**Comment by theflogat** [comment]
Just provide a redstone signal

**Comment by Logos01** [comment]
Did you even read the described behaviors?  How could I provide a redstone signal to a machine that can't even be placed in the world, for example?

Also -- I tried that for the various RF/MJ producers, and they did not operate.

**Comment by theflogat** [comment]
Mots of the machines have GUIs for me.
Node fabricators need power and essentia to operate (either auraum and taint to create a node or different essentia to add to the node). They get activated by being right-clicked with a wand.
Nodes have to be above the node dynamo and the latter needs to be receiving a redstone signal to operate.
Again, give a redstone signal to the essentia dynamo for it to work.
Blood dynamos don't use LP, they use liquid blood. Again redstone signal.
Bellows need to be exactly right-clicked on the block they attach to.

Also, please don't be so rude, making a mod is hard and not very rewarding. We don't owe you anything.

**Comment by Logos01** [comment]
Right.  None of those things work.  Attempting to right-click the node fabricator crashes the client.  It doesn't matter where the node is in relation to the node dynamo, nor whether it receives a redstone signal -- it doesn't operate.  

Again, giving redstone signal to the essentia dynamo doesn't work.

Blood dynamos do not receive liquid blood. With or without redstone signal.

It does not matter where or how you attempt to place the bellows, including placing them in the exact face of the Infernal Furnace; they will not place.

Essentia coils can be placed and render the connection to essentia tubes properly, but do not transmit essentia.

No machines have any GUI of any kind.  Nothing operates. 

Etc., etc., etc..

This has been replicated by myself over three modpack releases of Resonant Rise, as well as by each of my players (there are 8.)

Please do not repeat "just give it a redstone signal" when it is clear that this has been tried repeatedly without success.

**Comment by theflogat** [comment]
Just a quick little question:
What version are you on? It might be because you aren't on lastest version which is 0.6.0 and that can be found here http://www.minecraftforum.net/forum...s/2127441-0-6-0-technomancy-an-expanded-bridge

**Comment by Logos01** [comment]
Yeah, Looks like ResonantRise is shipping with TECHNOMANCY 0.5.0A4.  I'll give the different version a shot.

**Comment by Logos01** [comment]
Correct link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2127441-0-6-0-technomancy-an-expanded-bridge

**Comment by Logos01** [comment]
I've given up on ATLaunccher / ResonantRise with this; I couldn't get it to load.  I've since tried loading 0.7.1 on a FTB Monster server.  While it loads fine on the client, the server crashes.

http://pastebin.com/02LMcyd2

(================
Caused by: java.lang.NoSuchFieldError: icons
        at democretes.blocks.machines.BlockProcessor.<init>(BlockProcessor.java:70)
        at democretes.blocks.machines.BlockProcessor$BlockBMProcessor.<init>(BlockProcessor.java:185)
        at democretes.blocks.TMBlocks.initBloodMagic(TMBlocks.java:128)
        at democretes.Technomancy.init(Technomancy.java:75)
================)

(For what it's worth; client-side I have been able to get the coils, dynamos, and node fabricator to work; but the energy condensor does not release its potentia regardless of the means tried.)
